name: Update STranslate Version

on:
  schedule:
    # 每天检查一次新版本
    - cron: '0 0 * * *'
  # 允许手动触发
  workflow_dispatch:

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Check for new releases and update files
        run: |
          # 获取 STranslate 仓库的最新 Release 版本
          LATEST_VERSION=$(curl -s https://api.github.com/repos/ZGGSONG/STranslate/releases/latest | jq -r .tag_name)
          echo "Latest STranslate version is $LATEST_VERSION"
          
          # 检查中文版 download.md 文件
          CN_VERSION=$(grep -oP "const version = '\K[^']+" vitepress/download.md)
          echo "Current version in Chinese file is $CN_VERSION"
          
          # 检查英文版 download.md 文件
          EN_VERSION=$(grep -oP "const version = '\K[^']+" vitepress/en/download.md)
          echo "Current version in English file is $EN_VERSION"
          
          # 检查是否需要更新
          CN_NEEDS_UPDATE=false
          EN_NEEDS_UPDATE=false
          
          if [ "$LATEST_VERSION" != "$CN_VERSION" ]; then
            echo "Chinese file needs update from $CN_VERSION to $LATEST_VERSION"
            CN_NEEDS_UPDATE=true
          fi
          
          if [ "$LATEST_VERSION" != "$EN_VERSION" ]; then
            echo "English file needs update from $EN_VERSION to $LATEST_VERSION"
            EN_NEEDS_UPDATE=true
          fi
          
          # 如果需要更新，执行更新操作
          CHANGES_MADE=false
          
          if [ "$CN_NEEDS_UPDATE" = true ]; then
            echo "Updating Chinese file version to $LATEST_VERSION"
            sed -i "s/const version = '$CN_VERSION'/const version = '$LATEST_VERSION'/g" vitepress/download.md
            CHANGES_MADE=true
          fi
          
          if [ "$EN_NEEDS_UPDATE" = true ]; then
            echo "Updating English file version to $LATEST_VERSION"
            sed -i "s/const version = '$EN_VERSION'/const version = '$LATEST_VERSION'/g" vitepress/en/download.md
            CHANGES_MADE=true
          fi
          
          # 如果有更改，提交并推送
          if [ "$CHANGES_MADE" = true ]; then
            git config --global user.name 'GitHub Actions Bot'
            git config --global user.email 'actions@github.com'
            git add vitepress/download.md vitepress/en/download.md
            git commit -m "Update STranslate version to $LATEST_VERSION"
            git push
            echo "Version(s) updated successfully to $LATEST_VERSION"
          else
            echo "No updates needed. All files already have the latest version: $LATEST_VERSION"
          fi
